# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa0ca1fa0efdfbe61b5d37b7fb1c5791b846fe6bfab69cb2720de2dd7502f56b9bd1183767fbb24979870fa4e345482dfcff48830173e2f6ca41f35032df42f3

test:
  secret_key_base: e740f73267a6e2ffe802090289e631799a0ca3cbbc1f60dba36961cbe2c0ffb5a767e4ea7928a7c26c4dc039b78b948860aa77ab574ad6beb08f424898e0843b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
